/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}'],
  theme: {
    fontFamily: {
      'aileron-light': ['"Aileron Light"', 'system-ui', 'sans-serif'],
      aileron: ['Aileron', 'system-ui', 'sans-serif'],
      'aileron-semibold': ['"Aileron SemiBold"', 'system-ui', 'sans-serif'],
      'aileron-bold': ['"Aileron Bold"', 'system-ui', 'sans-serif'],
    },
    extend: {
      colors: {
        'primary-earth': '#002e40',
        'primary-stone': '#ad9c70',
        'primary-white': '#fff',
        'primary-black': '#000',
        'alternate': '#505050',
        'alternate-disabled': '#b5b5b5',
        'secondary-lichen': '#99b096',
        'secondary-sky': '#7391bf',
        'secondary-sea': '#528791',
        'secondary-grass': '#8cb052',
        'secondary-haze': '#d48080',
        'secondary-clay': '#b87d33',
        'secondary-amber': '#f0a845',
        'secondary-sand': '#c4bd9c',
        'secondary-rock': '#a8a8a1',
        'secondary-earth': '#998a82',
        'secondary-slate': '#808082',
        'secondary-red': '#eb5757',
        'mono-black': '#252525',
        'mono-grey-1': '#e1e1e1',
        'mono-grey-2': '#e5e5e5',
        'mono-grey-3': '#b5b5b5',
        'mono-grey-4': '#505050',
        'state-success': '#007b40',
        'state-error': '#f03d3e',
        'state-warn': '#f0a845',
      },
      screens: {
        '3xl': '1830px',
      },
    },
  },
  plugins: [],
};
